### ISSUE TITLE
How can I handle a deploy for a pull request?

### ISSUE THREAD

**Issue by phaberest** [caprover/deploy-from-github#10]
Hi guys and thank you for all the goodness, I really enjoy using Caprover!

I was wondering if and how would it be possible to deploy every time there's a new pull request to a testing/staging environment that corresponds to a url like `name-of-the-branch--caproverappname.myserver.com`

Ideally I would need to be able to destroy the new created env once the PR gets merged or closed, but this is not a priority.

Is this something I can achieve with this action?

**Comment by githubsaturn** [comment]
Hi @phaberest  - unfortunately this is not quite possible using the built in functionality. CapRover doesn't support automatic creation of apps on pull request. It's something that technically can be done via API and lots of scripting, but it's not a built in functionality.
