### ISSUE TITLE
NEEDS ATTENTION: Setting up Github Container Package releases

### ISSUE THREAD

**Issue by maietta** [caprover/deploy-from-github#3]
Glad I could contribute with all the suggested changes. Much thanks for accepting the project.

I've been working to try and solve why the package "deploy-from-github" hasn't been showing up. I think I know why, but I am not 100% sure. It's been hell to try and track down just exactly what is going on.

It's been so long since I needed to do anything with Github Container Registry that I had completely forgotten this important step to getting this Github Action usable for the general public.

I am submitting another PR as well, with a simpler workflow to create and push docker images to the Github Registry.

**Comment by maietta** [comment]
Hi @githubsaturn,

We need to have you configure this repository so that it can deploy packages to the Github Container Registry that we can begin to use this project.

Visit https://github.com/orgs/admin-toolbox/packages?ecosystem=container and find the package "deploy-from-caprover"

Use the Link Connect Repository to link the package to the Repo.

![image](https://user-images.githubusercontent.com/11745020/182627624-37de19bb-a15a-40aa-a68e-ddd1d0452a62.png)

Adjust the Package Settings for to allow this Package to have access to Github Actions. Find and attach the repo "deploy-from-caprover" using the search.

![image](https://user-images.githubusercontent.com/11745020/182628543-0f83c252-eba3-4ce1-a346-9f8d8ef293b8.png)

Once that's done, you need to adjust the Role:Read to Role:Write.

You may need to visit the Actions tab for the project and trigger a build. In a few seconds the build will be completed.

I'm not sure what the last step is to get the packages to show.

**Comment by maietta** [comment]
So basically @githubsaturn, you'll need to visit your organization's main page and find the "Packages" tab.

Once there, you'll see the deploy-from-github container package.

You need to do two things:

- Possibly required to attach the container package to the repository.
- Allow the container to be edited via Github Actions with Role:Write instead of Role:Read.

Once this is one, I think the package will finally be public but I'm almost certain it exists already.

**Comment by githubsaturn** [comment]
Sounds good. Just left a minor comment on your PR.

**Comment by maietta** [comment]
Good point and now the ball is back in your court.

**Comment by maietta** [comment]
Thanks, @githubsaturn!

I hope to get better with this Github Workflows and Actions metadata stuff as I have many projects that will need better CI/CD tooling.

Your help in all this is greatly appreciated.
